version: '3'
services:
  back:
    build: ./chatDBServer
    container_name: chat-server
    # restart: always
    volumes:
      - ./chatDBServer:/app
    ports:
      - 8080:8080
    networks:
      - chat-network
    working_dir: /app
    command: uvicorn chatDBServer.main:app --reload  --host 0.0.0.0 --port 8080


  front:
    build: ./chatGUI
    tty: true
    volumes:
      - ./chatGUI:/app
    ports:
      - 5173:5173
    networks:
      - chat-network
    working_dir: /app
    depends_on:
      - back
    command: yarn dev

networks:
  chat-network:
    driver: bridge